### PR TITLE
CSS changes for responsive design

### PR DESCRIPTION
**Pull request by zedhaque**
## Purpose

This PR introduces changes in the CSS files to enhance responsiveness in the chat app, supporting the most common breakpoints. Additionally, it transitions styling units from pixels to rem/em for better scalability across devices. This PR does not include the implementation of a sticky header or any other changes requiring modifications to .tsx files; those will be addressed in a subsequent PR.

https://github.com/Azure-Samples/azure-search-openai-demo/issues/1458

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[X] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[X] No
```

## Type of change

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [x] The current tests all pass (`python -m pytest`).
- [x] I added tests that prove my fix is effective or that my feature works
- [ ] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [ ] I ran `python -m mypy` to check for type errors
- [ ] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Comment by pamelafox** [comment]
Thanks so much @zedhaque ! I'll take a look at this soon. I might try to run our Playwright tests against it, since it's in theory easy to tell Playwright to test mobile size configurations.

**Comment by pamelafox** [comment]
* I think the hamburger menu is the only way to reliably fit the options at low sizes. The world has collectively agreed.
* Yes, let's just use "Azure OpenAI + AI Search" and drop the other one.
* I think we can drop GitHub logo/link.

**Comment by pamelafox** [comment]
Let me know when this is ready for re-review!

**Comment by mattgotteiner** [comment]
Thanks @zedhaque  this is great!

**Review by pamelafox — APPROVED** [review]
Thanks @zedhaque, this looks great! I updated the E2E tests so they're working now, and they test the app at various sizes (optionally clicking burger menu when needed). Will merge now.
If you have time to send a PR with updated screenshots with the headers change, that'd be great.

**Pull request merged**
