### PR TITLE
feat: Add Dutch (nl-NL) translations.json and update config.json

### PR DESCRIPTION
**Pull request by jeannotdamoiseaux**
## Purpose

This update adds support for the Dutch language in the application. It includes translations of the user interface and labels to Dutch, enabling a more accessible experience for Dutch-speaking users.

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[ X ] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[ X ] No
```

## Type of change

```
[ ] Bugfix
[ X ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [ ] The current tests all pass (`python -m pytest`).
- [ ] I added tests that prove my fix is effective or that my feature works
- [ ] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [ ] I ran `python -m mypy` to check for type errors
- [ ] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Comment by jeannotdamoiseaux** [comment]
I encountered one test failure when running python -m pytest, but this issue appears unrelated to my changes.

The failing test is:
`FAILED tests/test_prepdocslib_textsplitter.py::test_sentencetextsplitter_list_parse_and_split - assert 1 > 1`

**Comment by jeannotdamoiseaux** [comment]
> @jeannotdamoiseaux please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Provincie Limburg"

**Comment by jeannotdamoiseaux** [comment]
@pamelafox Could you review this PR?

**Comment by pamelafox** [comment]
@jeannotdamoiseaux Thanks for the PR! A few questions:
1) I assume that you wrote these translations yourself, i.e. you're a native Dutch speaker
2) Will you be available to translate strings in the future, i.e. can I tag you on PRs that add new Dutch strings? I don't know if I have any Dutch speaking colleagues, so we need to make sure we have a strategy to continue support for nl
3) Can you provide a screenshot of the app working with nl? Sometimes folks have contributed strings but not actually confirmed that they worked in the app, so I want to make sure.

**Comment by jeannotdamoiseaux** [comment]
> @jeannotdamoiseaux Thanks for the PR! A few questions:
> 
> 1. I assume that you wrote these translations yourself, i.e. you're a native Dutch speaker
> 2. Will you be available to translate strings in the future, i.e. can I tag you on PRs that add new Dutch strings? I don't know if I have any Dutch speaking colleagues, so we need to make sure we have a strategy to continue support for nl
> 3. Can you provide a screenshot of the app working with nl? Sometimes folks have contributed strings but not actually confirmed that they worked in the app, so I want to make sure.

	1.	Yes, I’m a native Dutch speaker and did these translations myself.
	2.	Sure, feel free to tag me in future PRs! I’m available to assist with new Dutch translations.
	3.	I’ll upload a screenshot demonstrating the app with Dutch translations by tomorrow.

**Comment by pamelafox** [comment]
Great, tests are passing on CI, so I'll approve and merge once screenshot is available. Thanks so much!

**Comment by jeannotdamoiseaux** [comment]
> Great, tests are passing on CI, so I'll approve and merge once screenshot is available. Thanks so much!

image

Does this look good to you?

**Review by pamelafox — APPROVED** [review]

**Comment by pamelafox** [comment]
Great, thank you!

**Pull request merged**
