### PR TITLE
Add Tooltips to Developer Settings

### LINKED ISSUE #1334: Add tool tips to settings in Developer Settings
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by john0isaac**
## Purpose

fix #1334

Thanks to @diberry, your tooltip works like a charm!

image

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[X] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[X] No
```

## Type of change

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [X] The current tests all pass (`python -m pytest`).
- [X] I added tests that prove my fix is effective or that my feature works
- [X] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [X] I ran `python -m mypy` to check for type errors
- [X] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Comment by pamelafox** [comment]
Thanks! I'll check this out locally and probably tweak the text a bit before merging. I was hoping there was a way of adding tooltips that wouldn't cause such a large diff, but I believe you and Dina that this is the correct way for this version of Fluent.

**Comment by pamelafox** [comment]
@john0isaac I checked out this branch and couldn't get tooltips to appear for some reason (I think that must have been what I encountered last time I tried a TooltipHost branch), so I found an alternate UI, which I'm proposing in https://github.com/Azure-Samples/azure-search-openai-demo/pull/1522

**Comment by john0isaac** [comment]
You need to hard reload the website after deploying.
Also you should wait ~10 mins after the deployment then attempt to refresh as the changes take sometime to appear.

But I'm okay with your proposal too.

**Comment by john0isaac** [comment]
I guess it's the hovering thing. You need to stand on the text for a bit before it shows up not just hover.
Yeah, I agree that yours is more discoverable.
Should I close this PR?

**Comment by pamelafox** [comment]
Sure, we can close this PR. Thanks for reviving the feature!

**Pull request closed without merging**
