### PR TITLE
Use AVM for all Cognitive Services accounts and services

### PR DESCRIPTION
**Pull request by tonybaloney**
## Purpose

This replaces the custom AZD/Core cognitive services module with the AVM Resource for cognitive services. Reduces the overall footprint of bicep. 

The provisioned resources should be the same.

### CODE REVIEW

**Comment by tonybaloney** [comment]
```default
ERROR: deployment failed: error deploying infrastructure: generating preview: error code: InvalidTemplateDeployment, message: The template deployment 'aoai-comparison-1721096584' is not valid according to the validation procedure. The tracking id is '24888db7-0asdasdas5'. See inner errors for details.. Details: code: UpdatingCustomDomainNotAllowed, message: Updating or disabling sub domain is not supported.
code: UpdatingCustomDomainNotAllowed, message: Updating or disabling sub domain is not supported.
```

**Comment by pamelafox** [comment]
I was wondering if it did the subdomain thing that we do (automatic setting based on name). You may need to do that yourself, it seems.

**Comment by tonybaloney** [comment]
> I was wondering if it did the subdomain thing that we do (automatic setting based on name). You may need to do that yourself, it seems.

I fixed that issue in [5f5f90a](https://github.com/Azure-Samples/azure-search-openai-demo/pull/1818/commits/5f5f90a5f4db0218d4aaca67a869a6d9f82a6577)

**Comment by tonybaloney** [comment]
Impact of changes:

screenshot 2024-07-16 at 14 32 03
screenshot 2024-07-16 at 14 33 27

**Comment by tonybaloney** [comment]
Dynamic Throttling is a feature that could cause additional cost: https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/scaling-strategies-for-large-scale-azure-cognitive-services/ba-p/3819520

**Comment by tonybaloney** [comment]
Additional detail on auto-scaling https://learn.microsoft.com/en-us/azure/ai-services/autoscale?tabs=portal

**Comment by tonybaloney** [comment]
Verified on the portal, neither of these properties have any effect on the deployed services

**Comment by tonybaloney** [comment]
> Did you research restrictOutboundNetworkAccess? I haven't found a good resource on exactly what features that'd limit for OpenAI, Document Intelligence, etc.

It doesn't seem to do anything for either. I don't have GPT-V on this deployment so it might be worth testing on that too

**Comment by pamelafox** [comment]
I deployed on my gpt vision environment, and both the chat and data ingestion work. These were all the changed resources (which included your other AVM change):

Screenshot 2024-07-16 at 10 07 07 AM

**Review by pamelafox — APPROVED** [review]

**Pull request merged**
