### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by Alok0406**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by pamelafox** [comment]
@Alok0406 This looks like an accidental PR. I see there are alot of documents in the data folder. Please note that this is a public repo, so those documents are now viewable publicly. Please ensure no confidential data has been revealed in them. We will close this PR.

**Comment by Alok0406** [comment]
Hi,
It was indeed a mistake , please can you help confirm that this is closed and no longer visible publicly.
Kind Regards,
Alok

**Comment by Alok0406** [comment]
@pamelafox  : could you please delete this branch

**Comment by pamelafox** [comment]
I am not an admin on this repo (just a contributor), but I've asked an admin to delete it.

**Pull request closed without merging**
