### PR TITLE
Add Azure Security for DevOps to CI Pipeline

### PR DESCRIPTION
**Pull request by tonybaloney**

### CODE REVIEW

**Comment by pamelafox** [comment]
Interesting, it errors on main.paramaters.json (as I expected, due to the azd ENV=default syntax) but still claims to upload the sarif, so I guess it works? Do the uploaded issues seem correct to you?

```
Error: An exception occurred while analyzing template /home/runner/work/azure-search-openai-demo/azure-search-openai-demo/infra/main.bicep with parameters file /home/runner/work/azure-search-openai-demo/azure-search-openai-demo/infra/main.parameters.json
```

**Comment by pamelafox** [comment]
Alerts: https://github.com/Azure-Samples/azure-search-openai-demo/security/code-scanning?query=pr%3A557+tool%3Atemplateanalyzer+is%3Aopen

**Comment by tonybaloney** [comment]
I've set it to only collect the errors now and not fail the build/CI process so we can work through them.

**Review by pamelafox — APPROVED** [review]

**Comment by pamelafox** [comment]
@tonybaloney Okay, I somehow hadn't realized that it could upload the sarif even after an error, that opens the door to using this one more repos. Next you can try to resolve one of the issues and see if the alert gets closed. :)

**Pull request merged**
