### PR TITLE
Add support for vector search for retrieval

### PR DESCRIPTION
**Pull request by pablocastro**
## Purpose
This change introduces support for using vector search during retrieval, using Azure Cognitive Search vector search and Azure OpenAI embeddings. This includes changes to the data preparation and ingestion process (to vectorize data using the OpenAI embeddings API) and during response generation where we now offer the option to do hybrid (vector + text), pure vector, or pure text retrieval.

## Does this introduce a breaking change?
```
[x] Yes
[ ] No
```

*Breaking change in that existing deployment won't work without either manually adding the embedding field to the index and populating it, or deleting the search index and re-running the ingestion process (prepdocs.py or prepdocs.ps1).

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Deploy this updated version, re-creating the search index as appropriate
* Issue a chat or question request, the default is already set to "hybrid" and will use vectors

### CODE REVIEW

**Review by chuwik — APPROVED** [review]

**Comment by SeaDude** [comment]
I looked through the code changes. I couldn't exactly tell where the embeddings are stored. Are they stored in the OpenAI service itself or is there a vector db I missed?

**Comment by kishorerv93** [comment]
@pablocastro  I tested this branch in my environment and i've got this error.

Retrieval Mode is vectors+hybrid

Screenshot 2023-05-19 at 4 37 28 PM

**Comment by pablocastro** [comment]
Odd, I just re-ran it and "It Works In My Machine" :) Can you take a stack trace from the server process to see what the error is? Also did you delete the index and re-created it by running the latest version of prepdocs.ps1?

**Comment by kishorerv93** [comment]
It worked now. I'm using `GPT-4-8k` and i had to update `chatreadretrieveread.py` >>`query_text = completion.choices[0].text` to `query_text = completion.choices[0].message.content ` and resolved the issue.

Also `prepdocs.sh` is missing few parameters 

`./scripts/.venv/bin/python ./scripts/prepdocs.py './data/*' --storageaccount "$AZURE_STORAGE_ACCOUNT" --container "$AZURE_STORAGE_CONTAINER" --searchservice "$AZURE_SEARCH_SERVICE" --openaiservice "$AZURE_OPENAI_SERVICE" --openaideployment "$AZURE_OPENAI_EMB_DEPLOYMENT" --index "$AZURE_SEARCH_INDEX" --formrecognizerservice "$AZURE_FORMRECOGNIZER_SERVICE" --tenant "$AZURE_TENANT_ID" -v`


Also on deploying on existing environment running `azd up` will not be succesful and must  to modify below bicep files

`infra/core/ai/cognitiveservices.bicep` 

`networkAcls: {
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }`
    
`infra/core/ai/formrecognizer.bicep` 

`networkAcls: {
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }`

@pablocastro  Great Work!!

**Comment by itmilos** [comment]
This is error I am getting 

openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: './scripts/prepdocs.sh'. : exit code: 1
itmilos@Miloss-MacBook-Air azure-search-openai-hydra %

**Comment by itmilos** [comment]
@pablocastro are we going to merge this into main ?

**Comment by itmilos** [comment]
@briansmi Could we get review for this ?

**Pull request merged**
