### PR TITLE
Update README.md to use in codespaces device code

### PR DESCRIPTION
**Pull request by olivMertens**
if not the codesapces azd auth login will fail

## Purpose

*  Launch azd auth login in codespaces will failed, added the correct process to permit use azd auth login in codespaces

## Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ x ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by pamelafox** [comment]
Codespaces should autodetect that device code must be used. If its not, thats a bug. Is this local Codespaces extension or in the browser?

cc @vhvb1989 @jongio

**Comment by vhvb1989** [comment]
> Codespaces should autodetect that device code must be used. If its not, thats a bug. Is this local Codespaces extension or in the browser?
> 
> cc @vhvb1989 @jongio

Within the browser @pamelafox .

azd checks if you are running in codespaces and in a web-browser and automatically set `use-device-code=true`

azd runs the command `code --status`, which would return: `"The --status argument is not yet supported in browsers"` and uses as a way to know about how vscode is running (web or non web).
As such, is vscode changes this behavior and implement `code --status` for the web, azd would stop knowing about it.

**Comment by olivMertens** [comment]
> Codespaces should autodetect that device code must be used. If its not, thats a bug. Is this local Codespaces extension or in the browser?
> 
> cc @vhvb1989 @jongio

in the browser

**Comment by pamelafox** [comment]
Can you screenshot what happened when you ran `azd auth login`? Can you also screenshot the results of running `code --status`?

**Comment by pamelafox** [comment]
Closing this as we haven't heard back.

**Pull request closed without merging**
