### PR TITLE
set content-type for streamed response

### PR DESCRIPTION
**Pull request by kaygu**
## Purpose
This PR changes the Content-Type of responses from the endpoint **/chat**. Previously, streamed responses where sent as  **text/html; charset=utf-8**, now they would be sent as **application/json**

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Do a request to the **/chat** endpoint and see that the Content-Type is different in the response header

### CODE REVIEW

**Comment by pamelafox** [comment]
I assume the lack of mime-type is causing an issue for you? Unfortunately there's no official mime-type, but "application/json" wouldn't be correct since this sends JSON lines. There's a discussion here: https://github.com/wardi/jsonlines/issues/9

I'd be fine with one of the mimetypes mentioned there, like application/jsonl, application/json-lines or application/x-ndjson.

**Comment by pamelafox** [comment]
I assume the lack of mime-type is causing an issue for you? Unfortunately there's no official mime-type, but "application/json" wouldn't be correct since this sends JSON lines. There's a discussion here: https://github.com/wardi/jsonlines/issues/9

I'd be fine with one of the mimetypes mentioned there, like application/jsonl, application/json-lines or application/x-ndjson.

**Comment by pamelafox** [comment]
I just tested application/json-lines and that worked fine. You're right that it's much better than the autodetected mime type in terms of how the browser network tab renders the response.

before:
Screenshot 2023-11-17 at 9 17 42 PM

after:
Screenshot 2023-11-17 at 9 18 23 PM

**Review by pamelafox — CHANGES_REQUESTED** [review]
Please change to application/json-lines

**Comment by kaygu** [comment]
Yes indeed it was mainly to display the json correctly into the web browser network tab. I did not know about json-lines mime-type. Thanks for the help

**Review by pamelafox — APPROVED** [review]

**Comment by pamelafox** [comment]
Thanks, merging!

**Pull request merged**
