### PR TITLE
Add support for Palm, Claude-2, Llama2, CodeLlama (100+LLMs) + A/B Testing in Prod

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Purpose

This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM allows you to use any LLM as a drop in replacement for `gpt-3.5-turbo` 

In addition LiteLLM client allows you to:
* A/B test LLMs in production 
* Dynamically control each LLMs prompt, temperature, top_k etc in our UI (no need to re-deploy code)
* Logging to view input/outputs for each LLM

Here's a link to a live demo of litellm client: https://admin.litellm.ai/ 

liteLLM-Ab-testing

## Does this introduce a breaking change?

```
[ ] Yes
[ *] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ *] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@pamelafox @hyoshioka0128 @tonybaloney can you please take a look at this PR when possible ? Happy to add more docs/tests if this initial commit looks good😊

**Comment by kcordoc** [comment]
@ishaan-jaff Any updates on this? I am looking forward to try liteLLM

**Comment by pamelafox** [comment]
Thank you for the PR. However, we're not currently looking to add an abstraction layer in front of the OpenAI calls, and it looks like devs who want to use litellm would be able to make the change themselves when needed by referencing this PR.

**Comment by ishaan-jaff** [comment]
Hi @kcordoc looks like they didn't want litellm merged here. If you're interested in using LiteLLM I'd love to personally help you using it

Here's a link to our github https://github.com/BerriAI/litellm
Discord: https://discord.com/invite/wuPM9dRgDw 

Let me know once you join - would love to help any way I can

**Pull request closed without merging**
