### PR TITLE
UI developer settings fix

### PR DESCRIPTION
**Pull request by vedenev**
## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[x] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[x] No
```

## Type of change

```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [ ] The current tests all pass (`python -m pytest`).
- [ ] I added tests that prove my fix is effective or that my feature works
- [ ] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [ ] I ran `python -m mypy` to check for type errors
- [ ] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

THIS IS SMALL CHANGE IN THE FRONTEND CODE. I TESTED IT MANUALLY. IT WORKS.

### CODE REVIEW

**Comment by vedenev** [comment]
The bug description:
What it does:
When I enter a category name in this text box, that category is excluded from the search results, as it should be. When I reopen the settings menu, the text box is empty instead of displaying what I've entered in it. However, the category will keep being excluded in the following searches until I enter some other value there.
What it should do:
The category name I've entered should be displayed in the text box to indicate that the category is being excluded from search results.

**Review by pamelafox — APPROVED** [review]
Thank you!

**Comment by vedenev** [comment]
@pamelafox 
@microsoft-github-policy-service agree [company="{Silo AI}"]

**Comment by vedenev** [comment]
@microsoft-github-policy-service agree company="Silo AI"

**Pull request merged**
