### PR TITLE
Keep the Approach base class up to date

### PR DESCRIPTION
**Pull request by gukoff**
## Purpose

Approach base class was not up to date with the newer `run()` schemas.

Using `abc`, we get more confidence that all subclasses conform with the declared schema.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by tonybaloney** [comment]
Please rebase with the new base signatures. I think that would make Chat and Ask the following:

```python
def run(self, history: Sequence[dict[str, str]], overrides: dict[str, Any]) -> Any:
  ...
```

```python
def run(self, q: str, overrides: dict[str, Any]) -> Any:
 ...
```

**Review by tonybaloney — CHANGES_REQUESTED** [review]
Please rebase with the new base signatures. I think that would make Chat and Ask the following:

```python
def run(self, history: Sequence[dict[str, str]], overrides: dict[str, Any]) -> Any:
  ...
```

```python
def run(self, q: str, overrides: dict[str, Any]) -> Any:
 ...
```

**Comment by gukoff** [comment]
@tonybaloney done!

**Comment by pamelafox** [comment]
@gukoff Thanks for this PR, I ended up making the same changes in a recent PR that changed the interface, so we don't need to merge this anymore.

**Pull request closed without merging**
