### PR TITLE
Update to tools parameter

### PR DESCRIPTION
**Pull request by tonybaloney**
`functions` is a deprecated argument. We should be using the tools parameter

### CODE REVIEW

**Review by srbalakr — APPROVED** [review]

**Comment by tonybaloney** [comment]
`openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid value for 'function_call': 'function_call' is only allowed when 'functions' are specified.", 'type': 'invalid_request_error', 'param': 'function_call', 'code': None}}`

**Comment by pamelafox** [comment]
I assume the OpenAI version we're supporting does support the new tools parameter?

**Comment by tonybaloney** [comment]
> I assume the OpenAI version we're supporting does support the new tools parameter?

Yes it does

**Review by pamelafox — APPROVED** [review]
Thank you!

**Pull request merged**
