### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by pamelafox**
## Purpose

Makes logs work in prod! See https://github.com/Kludex/uvicorn-worker/pull/18 for details

Screenshot 2024-07-31 at 7 32 32 AM

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[X] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[Z]X ] No
```

## Type of change

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [x] The current tests all pass (`python -m pytest`).
- [ ] I added tests that prove my fix is effective or that my feature works
- [x] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [x] I ran `python -m mypy` to check for type errors
- [x] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Review by mattgotteiner — APPROVED** [review]

**Comment by TaylorN15** [comment]
@pamelafox - should the logging functions in other areas be updated too? e.g. [here](https://github.com/Azure-Samples/azure-search-openai-demo/blob/7b55ad2b4cb4911141a69963a230ee79fd2f2b41/app/backend/error.py#L24) and [here](https://github.com/Azure-Samples/azure-search-openai-demo/blob/7b55ad2b4cb4911141a69963a230ee79fd2f2b41/app/backend/decorators.py#L29)

**Comment by pamelafox** [comment]
@TaylorN15 Good question - I think I may have attempted to change those to use the app logger, but gotten an error due to them happening outside of the app context (like during the streamed response for the error handling function). Fortunately since they're error-level, we *should* see them show up in the logs regardless.

A better fix might be to drop gunicorn and only use uvicorn. I've done that for a few other containerized apps, but am hoping that App Service will add an env variable like WEB_CONCURRENCY that makes it easy to change the worker count based on the number of cores.

**Comment by TaylorN15** [comment]
Ah yes, you're right. You'll get an error as it's outside of the app context. 

Honestly, I'm considering moving to FastAPI as I've been having some issues with our prod deployment and it appears to be related to gunicorn, but it's unclear.

**Comment by pamelafox** [comment]
We can also run Quart apps with uvicorn. For either Quart or FastAPI, we still need to set the number of workers somehow to take advantage of the host machine's cores, but we could hardcode that for the default sku, or just write a clever shell script.

We could also just port this app to FastAPI (I know a few devs have!), I just find that some things are a bit harder in FastAPI than in Quart (static files, middleware, etc), per my blog at https://blog.pamelafox.org/2024/07/should-you-use-quart-or-fastapi-for-ai.html

**Pull request merged**
