### PR TITLE
Update links and clean up tasks

### PR DESCRIPTION
**Pull request by pamelafox**
## Purpose

Two unrelated cleanups:
1) Update links now that techcommunity blog has changed URLs. The current URls work but require a 301 redirect, so our link checker doesn't realize they work, plus they take a second to redirect.
2) Remove the dotenv dependency from tasks.json as that produces an error in Codespaces, and is no longer needed as we load in the azure env ourselves.

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[X] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[X] No
```

## Type of change

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

N/A

### CODE REVIEW

**Comment by pamelafox** [comment]
@john0isaac Do you know why it's still reporting broken for the updated links? I get 200 when I curl them locally.

**Comment by john0isaac** [comment]
They rolled out an update for tech community yesterday, I will investigate and fix this in the next couple of hours.

**Comment by pamelafox** [comment]
@john0isaac The new platform seems to return 400 for programmatic requests:

>>> response = requests.head("[https://techcommunity.microsoft.com/blog/azurearchitectureblog/azure-opena\](https://techcommunity.microsoft.com/blog/azurearchitectureblog/azure-opena/)
i-landing-zone-reference-architecture/3882102")
>>> response.status_code
400
>>> response
<Response [400]>

So I think it has to be added to the list of uncheckable domains..unless there's some way to pass in a header that'll get a 200.

**Comment by pamelafox** [comment]
I've sent a PR to add techcommunity to the uncheckable list:
https://github.com/john0isaac/markdown-checker/pull/78

**Review by mattgotteiner — APPROVED** [review]

**Pull request merged**
