### PR TITLE
feat: add low cost browser text to speech output using WebSpeechAPI

### PR DESCRIPTION
**Pull request by john0isaac**
## Purpose
This PR adds the optional feature to enable the built into browsers text to speech optional feature by setting the `USE_SPEECH_OUTPUT_BROWSER` boolean.

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[x] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[x] No
```

## Type of change

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [x] The current tests all pass (`python -m pytest`).
- [-] I added tests that prove my fix is effective or that my feature works
- [-] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [-] I ran `python -m mypy` to check for type errors
- [x] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Comment by john0isaac** [comment]
todo: test, add docs

**Comment by pamelafox** [comment]
Thank you! Code looks good from a first glance, I'll check out the branch myself locally and see if I notice anything while using it.

**Comment by john0isaac** [comment]
I tried to make the naming match your `AzureSpeechOutput` in case you want to merge it in one file and do the checks there.
IMHO, the way it is now is cleaner to customize as the features doesn't overlap.

**Comment by john0isaac** [comment]
Weird, I did run `pre-commit run --all-files`.

**Review by pamelafox — APPROVED** [review]
Great code change! Everything works well, looks good, and is cleanly implemented. I tried it out locally and deployed (https://app-backend-ixehwdxj5j4oe.azurewebsites.net/), all seems well.

**Pull request merged**
