### PR TITLE
Add scheduler package

### LINKED ISSUE #671: ERROR: failed packaging service 'backend': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '2', Path: 'Temp\azd-prepackage-3470486931.ps1'. : exit code: 2
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by mattmsft**
## Purpose

* Resolve #671 

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by pamelafox** [comment]
The tests failed after the last merge just due to an API difference, the code isn't broken. So you could fix that or wait for me to PR a fix (later tonight). 

It'd be great if we could enable the setting where GitHub offers to merge in the latest from main, I miss having that on this repo. (I don't have the admin permission to change that, you may not either).

**Comment by mattmsft** [comment]
> The tests failed after the last merge just due to an API difference, the code isn't broken. So you could fix that or wait for me to PR a fix (later tonight).
> 
> It'd be great if we could enable the setting where GitHub offers to merge in the latest from main, I miss having that on this repo. (I don't have the admin permission to change that, you may not either).

Odd - i have merged and it's not working.

**Comment by mattmsft** [comment]
> > The tests failed after the last merge just due to an API difference, the code isn't broken. So you could fix that or wait for me to PR a fix (later tonight).
> > It'd be great if we could enable the setting where GitHub offers to merge in the latest from main, I miss having that on this repo. (I don't have the admin permission to change that, you may not either).
> 
> Odd - i have merged and it's not working.

Yes i have checked out main and it's still failing the tests

**Comment by pamelafox** [comment]
Sorry, what I mean is this:

* I had a messagebuilder branch where all the tests passed
* Once I merged the branch with main, the tests stopped passing due to a change that had happened in the interim that my branch didnt account for with its new tests. So, tests now fail on main.
* One way to prevent this is to enable GitHub option "Always suggest updating pull request branches " since then I would have merged from main before merging my PR and seen the test breakage.

So yeah they're broken now. Fix should just be to change the constructor in the new test to have query_speller and query_language.

**Review by pamelafox — APPROVED** [review]

**Pull request merged**
