### PR TITLE
Adding CSV parser feature

### PR DESCRIPTION
**Pull request by saravana87**
## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[x] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by [this tutorial](https://learn.microsoft.com/azure/developer/python/get-started-app-chat-template)
which includes deployment, settings and usage instructions. If text or screenshot need to change in the tutorial,
check the box below and notify the tutorial author. A Microsoft employee can do this for you if you're an external contributor.

```
[ ] Yes
[x] No
```

## Type of change

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Code quality checklist

See [CONTRIBUTING.md](https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr) for more details.

- [x] The current tests all pass (`python -m pytest`).
- [x] I added tests that prove my fix is effective or that my feature works
- [x] I ran `python -m pytest --cov` to verify 100% coverage of added lines
- [x] I ran `python -m mypy` to check for type errors
- [x] I either used the pre-commit hooks or ran `ruff` and `black` manually on my code.

### CODE REVIEW

**Comment by saravana87** [comment]
@microsoft-github-policy-service agree

**Comment by pamelafox** [comment]
Hi @saravana87, thanks for this PR! This looks useful, having a local CSV parser. If this is an intentional PR for merging into main, can you edit the title and description to describe it fully?

**Comment by saravana87** [comment]
> Can you also add a test? You can copy test_htmlparser.py and adapt that to CSV examples instead. Thank you!

Thank you. I will work on this and let you know.

**Comment by saravana87** [comment]
> Can you also add a test? You can copy test_htmlparser.py and adapt that to CSV examples instead. Thank you!

I have added the test_csvparser.py
https://github.com/saravana87/azure-search-openai-demo/blob/main/tests/test_csvparser.py

**Comment by pamelafox** [comment]
@saravana87  Great, can you push that to this branch? That seems to be in your main branch, not dev01.

**Comment by pamelafox** [comment]
It looks like your file also needs formatting, see guide to using ruff in https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/CONTRIBUTING.md#submit-pr

**Comment by saravana87** [comment]
> @saravana87 Great, can you push that to this branch? That seems to be in your main branch, not dev01.

Yes, I have formatted the files. Let me close this pull request and I will raise another pull request from the Main branch.

**Pull request closed without merging**
