### PR TITLE
ChatCompletion to use GPT-4 or GPT-3.5-16k

### PR DESCRIPTION
**Pull request by kishorerv93**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ X] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by kishorerv93** [comment]
@pamelafox  @pablocastro @srbalakr can you review this PR?

**Comment by kishorerv93** [comment]
> @kishorerv93 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Siemens Healthineers"]

**Comment by kishorerv93** [comment]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Siemens Healthineers"

**Comment by kishorerv93** [comment]
> > @kishorerv93 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> > ```
> > @microsoft-github-policy-service agree [company="Siemens Healthineers"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Options:
> > > 
> > > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > > 
> > > ```
> > > @microsoft-github-policy-service agree
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > > 
> > > ```
> > > @microsoft-github-policy-service agree company="Microsoft"
> > > ```
> > 
> > 
> > Contributor License Agreement
> 
> @microsoft-github-policy-service agree [company="Siemens Healthineers"]

**Comment by pamelafox** [comment]
@kishorerv93 There is a pending PR that updates this sample to use the ChatCompletion API:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/385
Can you patch that PR in and see that it works for GPT-4 for you?
If not, let us know what doesn't work. I don't think the sample should default to GPT-4 since not everyone has that, and it's more expensive, but ideally the only change needed would be in the Bicep configuration.
Thanks!

**Pull request closed without merging**
